import { WeekDaySchema } from './WeekDay.Schema';

export const weekDayData: WeekDaySchema[] = [
  {
    id: 1,
    day: 'Lundi',
    color: '#006400',
    selectedPersonMatin: 'Charlie',
    selectedPersonMidi: 'Lili',
    selectedPersonSoir: '',
  },
  {
    id: 2,
    day: 'Mardi',
    color: '#008000',
    selectedPersonMatin: 'Charlie',
    selectedPersonMidi: 'Lili',
    selectedPersonSoir: 'Géraldine',
  },
  {
    id: 3,
    day: 'Mercredi',
    color: '#8b4513',
    selectedPersonMatin: 'Charlie',
    selectedPersonMidi: 'Lili',
    selectedPersonSoir: 'Géraldine',
  },
  {
    id: 4,
    day: 'Jeudi',
    color: '#708090',
    selectedPersonMatin: 'Manu',
    selectedPersonMidi: '',
    selectedPersonSoir: 'Géraldine',
  },
  {
    id: 5,
    day: 'Vendredi',
    color: '#228b22',
    selectedPersonMatin: 'Charlie',
    selectedPersonMidi: 'Lili',
    selectedPersonSoir: 'Manu',
  },
  {
    id: 6,
    day: 'Samedi',
    color: '#8fbc8f ',
    selectedPersonMatin: 'Manu',
    selectedPersonMidi: 'Charlie',
    selectedPersonSoir: 'Géraldine',
  },
  {
    id: 7,
    day: 'Dimanche',
    color: '#006400',
    selectedPersonMatin: 'Lili',
    selectedPersonMidi: 'Charlie',
    selectedPersonSoir: 'Géraldine',
  },
];
